name: 'CD'

on:
  workflow_run:
    workflows: ['Test Report']                     # runs after CI workflow
    branches: [ main ]
    types:
      - completed

jobs:
  publish:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: json2record
        path: artifact/
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish
      run: dotnet nuget push artifact/ --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
    
    
