name: 'CI'

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build json2record
      run: dotnet build --no-restore --configuration Release json2record
    - name: Pack json2record
      run: dotnet pack --no-build --configuration Release json2record
    - name: Upload json2record
      uses: actions/upload-artifact@v2
      with:
        name: json2record
        path: json2record/nupkg/
    - name: Install json2record
      run: dotnet tool install --global --add-source json2record/nupkg/ json2record
    - name: Run Tests
      run: dotnet test json2record.tests --logger trx --configuration Release --verbosity normal --results-directory tests
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-test-results
        path: tests
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}