name: 'CI'

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build dtolab
      run: dotnet build --no-restore --configuration Release dtolab.console
    - name: Pack dtolab
      run: dotnet pack --no-build --configuration Release dtolab.console
    - name: Upload dtolab
      uses: actions/upload-artifact@v2
      with:
        name: dtolab
        path: dtolab.console/nupkg/
    - name: Install dtolab
      run: dotnet tool install --global --add-source dtolab.console/nupkg/ dtolab
    - name: Run dtolab
      run: dotnet test dtolab.tests --logger trx --no-restore --configuration Release --verbosity normal --results-directory tests
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-test-results
        path: tests
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
  
  publish:
    
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }} 
    needs: build-test
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: dtolab
        path: artifact/
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Publish
      run: dotnet nuget push artifact/ --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}