name: .NET

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: 'echo "$(pwd)"'
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore json2record
    - name: Test
      run: dotnet test --verbosity normal json2record.tests
      
  publish:
    
    runs-on: ubuntu-latest
    
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Pack
      run: dotnet pack json2record
    - name: Publish
      run: dotnet nuget push https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
    
    
