name: .NET

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: 'echo "$(pwd)"'
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore json2record
    - name: Run Tests
      run: dotnet test json2record.tests --logger trx --verbosity normal --results-directory tests
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-test-results
        path: tests
        # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
      
  publish:
    
    runs-on: ubuntu-latest
    
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Pack
      run: dotnet pack json2record
    - name: Publish
      run: dotnet nuget push ./json2record/nupkg/ --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
    
    
