name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
      - master

jobs:
  terraform:
    name: 'Deploy static web app'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy static web app
        id: deploy-swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          app_location: "/json2record.swa" # App source code path
          # api_location: "/json2record.func" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######