name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - dev
      - master

env:
  AZURE_FUNCTIONAPP_NAME: json2record.func  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './json2record.func'    # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '5.0.0'              # set this to the dotnet version to use

jobs:
  deploy:
    name: 'Deploy static web app'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.FUNC_PUBLISH_PROFILE }}

      - name: Deploy static web app
        id: deploy-swa
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.SWA_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          app_location: "/json2record.swa" # App source code path
          # api_location: "/json2record.func" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######